### ISSUE TITLE
pyTermTk windows support

### ISSUE THREAD

**Issue by ceccopierangiolieugenio** [Vasc01/2d-cad-exercise#12]
Hi, I know that I should not jump in,
but if you are still interested I am working to support Windows with pyTermTk

https://github.com/Vasc01/2d-cad-exercise/assets/8876552/18c8b04c-e30a-4b13-9839-2dfbe781391c

**Comment by Vasc01** [comment]
Hi,
For this project I have already set my mind on _curses_, but I will certainly keep _pyTermTk_ in mind for future projects. I haven't used it yet but it looks very promising.
